goog.require('Blockly.Blocks');
goog.require('Blockly.Types');

goog.provide('Blockly.Blocks.audio_spencer');

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_playsample",
		message0: "play audio sample %1",
		args0: [
			{
				type: "input_value",
				name: "SAMPLE",
				check: "Spencer_Audio_Sample"
			}
		],
		previousStatement: null,
		nextStatement: null,
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Starts playing the given audio sample",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_stopsample",
		message0: "stop playing audio",
		previousStatement: null,
		nextStatement: null,
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Stops playing the current audio sample",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_done",
		message0: "when current sample is done",
		message1: "%1",
		args1: [{
			type: "input_statement",
			name: "CODE"
		}],
		previousStatement: null,
		nextStatement: null,
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Executes blocks when the currently playing sample is done.",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_error",
		message0: "error %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["mess", "mess"],
					["no WiFi", "wifi"],
					["no internet", "net"],
					["service down", "service"],
					["didn't understand", "noIntent"]
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Error samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_generic",
		message0: "generic %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["and", "and"],
					["first startup", "firstStartup"],
					["entering configuration mode", "setupModeEntering"],
					["configuration mode", "setupMode"],
					["update available", "update"]
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Generic samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_level",
		message0: "level %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["low", "low"],
					["medium", "medium"],
					["high", "high"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Level samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_special",
		message0: "special %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["startup", "startup"],
					["badum 0", "badum0"],
					["badum 1", "badum1"],
					["badum 2", "badum2"],
					["badum 3", "badum3"],
					["random noise 0", "randomNoise0"],
					["random noise 1", "randomNoise1"],
					["random noise 2", "randomNoise2"],
					["random noise 3", "randomNoise3"],
					["random noise 4", "randomNoise4"],
					["random noise 5", "randomNoise5"],
					["random noise 6", "randomNoise6"],
					["random noise 7", "randomNoise7"],
					["random noise 8", "randomNoise8"],
					["random noise 9", "randomNoise9"],
					["random noise 10", "randomNoise10"],
					["random noise 11", "randomNoise11"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Special samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_time",
		message0: "time %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["AM", "AM"],
					["PM", "PM"],
					["second", "second"],
					["seconds", "seconds"],
					["minute", "minute"],
					["minutes", "minutes"],
					["the time is", "The_time_is"],
					["it's the", "It's_the"],
					["of", "of"],
					["under", "under"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Time related samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_weather",
		message0: "weather %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["the temperature is", "temperature_is"],
					["minus", "minus"],
					["degrees celsius", "celsius"],
					["degrees fahrenheit", "fahrenheit"],
					["it's sunny outside", "sunny"],
					["the skies are clear", "clear"],
					["it's a bit cloudy outside", "cloudy"],
					["it's foggy outside", "foggy"],
					["it's raining outside", "rainy"],
					["it's snowy outside", "snowy"],
					["the temperature will be around", "forecast"],
					["it will be sunny", "forecastSunny"],
					["the skies will be mostly clear", "forecastClear"],
					["it will be a bit cloudy", "forecastCloudy"],
					["it's going to be a foggy", "forecastFoggy"],
					["there is a chance of rainfall", "forecastRain"],
					["there is a chance of snowfall", "forecastSnowy"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Weather related samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_month",
		message0: "month %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["January", "1"],
					["February", "2"],
					["March", "3"],
					["April", "4"],
					["May", "5"],
					["June", "6"],
					["July", "7"],
					["August", "8"],
					["September", "9"],
					["October", "10"],
					["November", "11"],
					["December", "12"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Month samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_weekday",
		message0: "weekday %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["Monday", "1"],
					["Tuesday", "2"],
					["Wednesday", "3"],
					["Thursday", "4"],
					["Friday", "5"],
					["Saturday", "6"],
					["Sunday", "7"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Weekday samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_number",
		message0: "number %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["0", "0"],
					["1", "1"],
					["2", "2"],
					["3", "3"],
					["4", "4"],
					["5", "5"],
					["6", "6"],
					["7", "7"],
					["8", "8"],
					["9", "9"],
					["10", "10"],
					["11", "11"],
					["12", "12"],
					["13", "13"],
					["14", "14"],
					["15", "15"],
					["16", "16"],
					["17", "17"],
					["18", "18"],
					["19", "19"],
					["20", "20"],
					["30", "30"],
					["40", "40"],
					["50", "50"],
					["60", "60"],
					["70", "70"],
					["80", "80"],
					["90", "90"],
					["100", "100"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Number samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_number_ordinal",
		message0: "ordinal number %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["1.", "1."],
					["2.", "2."],
					["3.", "3."],
					["4.", "4."],
					["5.", "5."],
					["6.", "6."],
					["7.", "7."],
					["8.", "8."],
					["9.", "9."],
					["10.", "10."],
					["11.", "11."],
					["12.", "12."],
					["13.", "13."],
					["14.", "14."],
					["15.", "15."],
					["16.", "16."],
					["17.", "17."],
					["18.", "18."],
					["19.", "19."],
					["20.", "20."],
					["30.", "30."],
					["40.", "40."],
					["50.", "50."],
					["60.", "60."],
					["70.", "70."],
					["80.", "80."],
					["90.", "90."],
					["100.", "100."],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Ordinal number samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_funpack",
		message0: "funpack %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["age0", "age0"],
					["age1", "age1"],
					["age2", "age2"],
					["age3", "age3"],
					["alexa0", "alexa0"],
					["alexa1", "alexa1"],
					["alexa2", "alexa2"],
					["alexa3", "alexa3"],
					["angrycrowd0", "angrycrowd0"],
					["angrycrowd1", "angrycrowd1"],
					["angrycrowd2", "angrycrowd2"],
					["angrycrowd3", "angrycrowd3"],
					["areyouok0", "areyouok0"],
					["areyouok1", "areyouok1"],
					["areyouok2", "areyouok2"],
					["areyouok3", "areyouok3"],
					["areyouskynet0", "areyouskynet0"],
					["areyouskynet1", "areyouskynet1"],
					["areyouskynet2", "areyouskynet2"],
					["areyouskynet3", "areyouskynet3"],
					["beammeupscotty0", "beammeupscotty0"],
					["beammeupscotty1", "beammeupscotty1"],
					["beammeupscotty2", "beammeupscotty2"],
					["beammeupscotty3", "beammeupscotty3"],
					["beatbox0", "beatbox0"],
					["beatbox1", "beatbox1"],
					["beatbox2", "beatbox2"],
					["beatbox3", "beatbox3"],
					["believeinaliens0", "believeinaliens0"],
					["believeinaliens1", "believeinaliens1"],
					["believeinaliens2", "believeinaliens2"],
					["believeinaliens3", "believeinaliens3"],
					["believeinlove0", "believeinlove0"],
					["believeinlove1", "believeinlove1"],
					["believeinlove2", "believeinlove2"],
					["believeinlove3", "believeinlove3"],
					["beyourboyfriend0", "beyourboyfriend0"],
					["beyourboyfriend1", "beyourboyfriend1"],
					["beyourboyfriend2", "beyourboyfriend2"],
					["beyourboyfriend3", "beyourboyfriend3"],
					["bigsby0", "bigsby0"],
					["bigsby1", "bigsby1"],
					["bigsby2", "bigsby2"],
					["bigsby3", "bigsby3"],
					["birdsound0", "birdsound0"],
					["birdsound1", "birdsound1"],
					["birdsound2", "birdsound2"],
					["birdsound3", "birdsound3"],
					["boyfriend0", "boyfriend0"],
					["boyfriend1", "boyfriend1"],
					["boyfriend2", "boyfriend2"],
					["boyfriend3", "boyfriend3"],
					["buyaboat0", "buyaboat0"],
					["buyaboat1", "buyaboat1"],
					["buyaboat2", "buyaboat2"],
					["buyaboat3", "buyaboat3"],
					["calldifferently0", "calldifferently0"],
					["calldifferently1", "calldifferently1"],
					["calldifferently2", "calldifferently2"],
					["calldifferently3", "calldifferently3"],
					["callmom0", "callmom0"],
					["callmom1", "callmom1"],
					["callmom2", "callmom2"],
					["callmom3", "callmom3"],
					["catsounds0", "catsounds0"],
					["catsounds1", "catsounds1"],
					["catsounds2", "catsounds2"],
					["catsounds3", "catsounds3"],
					["celebritycrush0", "celebritycrush0"],
					["celebritycrush1", "celebritycrush1"],
					["celebritycrush2", "celebritycrush2"],
					["celebritycrush3", "celebritycrush3"],
					["changename0", "changename0"],
					["changename1", "changename1"],
					["changename2", "changename2"],
					["changename3", "changename3"],
					["cheatcode0", "cheatcode0"],
					["cheatcode1", "cheatcode1"],
					["cheatcode2", "cheatcode2"],
					["cheatcode3", "cheatcode3"],
					["chikensound0", "chikensound0"],
					["chikensound1", "chikensound1"],
					["chikensound2", "chikensound2"],
					["chikensound3", "chikensound3"],
					["color0", "color0"],
					["color1", "color1"],
					["color2", "color2"],
					["color3", "color3"],
					["compliment0", "compliment0"],
					["compliment1", "compliment1"],
					["compliment2", "compliment2"],
					["compliment3", "compliment3"],
					["cortana0", "cortana0"],
					["cortana1", "cortana1"],
					["cortana2", "cortana2"],
					["cortana3", "cortana3"],
					["cowsound0", "cowsound0"],
					["cowsound1", "cowsound1"],
					["cowsound2", "cowsound2"],
					["cowsound3", "cowsound3"],
					["creator0", "creator0"],
					["creator1", "creator1"],
					["creator2", "creator2"],
					["creator3", "creator3"],
					["didyoufart0", "didyoufart0"],
					["didyoufart1", "didyoufart1"],
					["didyoufart2", "didyoufart2"],
					["didyoufart3", "didyoufart3"],
					["dislike0", "dislike0"],
					["dislike1", "dislike1"],
					["dislike2", "dislike2"],
					["dislike3", "dislike3"],
					["doabarrelroll0", "doabarrelroll0"],
					["doabarrelroll1", "doabarrelroll1"],
					["doabarrelroll2", "doabarrelroll2"],
					["doabarrelroll3", "doabarrelroll3"],
					["dogsound0", "dogsound0"],
					["dogsound1", "dogsound1"],
					["dogsound2", "dogsound2"],
					["dogsound3", "dogsound3"],
					["donkeysound0", "donkeysound0"],
					["donkeysound1", "donkeysound1"],
					["donkeysound2", "donkeysound2"],
					["donkeysound3", "donkeysound3"],
					["duckgeesesound0", "duckgeesesound0"],
					["duckgeesesound1", "duckgeesesound1"],
					["duckgeesesound2", "duckgeesesound2"],
					["duckgeesesound3", "duckgeesesound3"],
					["favoritefood0", "favoritefood0"],
					["favoritefood1", "favoritefood1"],
					["favoritefood2", "favoritefood2"],
					["favoritefood3", "favoritefood3"],
					["favoritesong0", "favoritesong0"],
					["favoritesong1", "favoritesong1"],
					["favoritesong2", "favoritesong2"],
					["favoritesong3", "favoritesong3"],
					["favouritemovie0", "favouritemovie0"],
					["favouritemovie1", "favouritemovie1"],
					["favouritemovie2", "favouritemovie2"],
					["favouritemovie3", "favouritemovie3"],
					["feeling0", "feeling0"],
					["feeling1", "feeling1"],
					["feeling2", "feeling2"],
					["feeling3", "feeling3"],
					["findphone0", "findphone0"],
					["findphone1", "findphone1"],
					["findphone2", "findphone2"],
					["findphone3", "findphone3"],
					["findrecipe0", "findrecipe0"],
					["findrecipe1", "findrecipe1"],
					["findrecipe2", "findrecipe2"],
					["findrecipe3", "findrecipe3"],
					["freetime0", "freetime0"],
					["freetime1", "freetime1"],
					["freetime2", "freetime2"],
					["freetime3", "freetime3"],
					["frogsound0", "frogsound0"],
					["frogsound1", "frogsound1"],
					["frogsound2", "frogsound2"],
					["frogsound3", "frogsound3"],
					["ghost0", "ghost0"],
					["ghost1", "ghost1"],
					["ghost2", "ghost2"],
					["ghost3", "ghost3"],
					["girlfriend0", "girlfriend0"],
					["girlfriend1", "girlfriend1"],
					["girlfriend2", "girlfriend2"],
					["girlfriend3", "girlfriend3"],
					["goatsheepsound0", "goatsheepsound0"],
					["goatsheepsound1", "goatsheepsound1"],
					["goatsheepsound2", "goatsheepsound2"],
					["goatsheepsound3", "goatsheepsound3"],
					["goodday0", "goodday0"],
					["goodday1", "goodday1"],
					["goodday2", "goodday2"],
					["goodday3", "goodday3"],
					["goodevening0", "goodevening0"],
					["goodevening1", "goodevening1"],
					["goodevening2", "goodevening2"],
					["goodevening3", "goodevening3"],
					["goodmorning0", "goodmorning0"],
					["goodmorning1", "goodmorning1"],
					["goodmorning2", "goodmorning2"],
					["goodmorning3", "goodmorning3"],
					["goodnight0", "goodnight0"],
					["goodnight1", "goodnight1"],
					["goodnight2", "goodnight2"],
					["goodnight3", "goodnight3"],
					["google0", "google0"],
					["google1", "google1"],
					["google2", "google2"],
					["google3", "google3"],
					["happybirthday0", "happybirthday0"],
					["happybirthday1", "happybirthday1"],
					["happybirthday2", "happybirthday2"],
					["happybirthday3", "happybirthday3"],
					["hello0", "hello0"],
					["hello1", "hello1"],
					["hello2", "hello2"],
					["hello3", "hello3"],
					["help0", "help0"],
					["help1", "help1"],
					["help2", "help2"],
					["help3", "help3"],
					["hi0", "hi0"],
					["hi1", "hi1"],
					["hi2", "hi2"],
					["hi3", "hi3"],
					["highfive0", "highfive0"],
					["highfive1", "highfive1"],
					["highfive2", "highfive2"],
					["highfive3", "highfive3"],
					["horoscope0", "horoscope0"],
					["horoscope1", "horoscope1"],
					["horoscope2", "horoscope2"],
					["horoscope3", "horoscope3"],
					["horsesound0", "horsesound0"],
					["horsesound1", "horsesound1"],
					["horsesound2", "horsesound2"],
					["horsesound3", "horsesound3"],
					["howdidyoulearnenglish0", "howdidyoulearnenglish0"],
					["howdidyoulearnenglish1", "howdidyoulearnenglish1"],
					["howdidyoulearnenglish2", "howdidyoulearnenglish2"],
					["howdidyoulearnenglish3", "howdidyoulearnenglish3"],
					["howwasyourday0", "howwasyourday0"],
					["howwasyourday1", "howwasyourday1"],
					["howwasyourday2", "howwasyourday2"],
					["howwasyourday3", "howwasyourday3"],
					["iamyourfather0", "iamyourfather0"],
					["iamyourfather1", "iamyourfather1"],
					["iamyourfather2", "iamyourfather2"],
					["iamyourfather3", "iamyourfather3"],
					["isthisreallife0", "isthisreallife0"],
					["isthisreallife1", "isthisreallife1"],
					["isthisreallife2", "isthisreallife2"],
					["isthisreallife3", "isthisreallife3"],
					["language0", "language0"],
					["language1", "language1"],
					["language2", "language2"],
					["language3", "language3"],
					["like0", "like0"],
					["like1", "like1"],
					["like2", "like2"],
					["like3", "like3"],
					["lionsound0", "lionsound0"],
					["lionsound1", "lionsound1"],
					["lionsound2", "lionsound2"],
					["lionsound3", "lionsound3"],
					["lonely0", "lonely0"],
					["lonely1", "lonely1"],
					["lonely2", "lonely2"],
					["lonely3", "lonely3"],
					["longtimenosee0", "longtimenosee0"],
					["longtimenosee1", "longtimenosee1"],
					["longtimenosee2", "longtimenosee2"],
					["longtimenosee3", "longtimenosee3"],
					["makesandwitch0", "makesandwitch0"],
					["makesandwitch1", "makesandwitch1"],
					["makesandwitch2", "makesandwitch2"],
					["makesandwitch3", "makesandwitch3"],
					["married0", "married0"],
					["married1", "married1"],
					["married2", "married2"],
					["married3", "married3"],
					["meaningoflife0", "meaningoflife0"],
					["meaningoflife1", "meaningoflife1"],
					["meaningoflife2", "meaningoflife2"],
					["meaningoflife3", "meaningoflife3"],
					["merrychristmas0", "merrychristmas0"],
					["merrychristmas1", "merrychristmas1"],
					["merrychristmas2", "merrychristmas2"],
					["merrychristmas3", "merrychristmas3"],
					["name0", "name0"],
					["name1", "name1"],
					["name2", "name2"],
					["name3", "name3"],
					["newonnetflix0", "newonnetflix0"],
					["newonnetflix1", "newonnetflix1"],
					["newonnetflix2", "newonnetflix2"],
					["newonnetflix3", "newonnetflix3"],
					["notbirthday0", "notbirthday0"],
					["notbirthday1", "notbirthday1"],
					["notbirthday2", "notbirthday2"],
					["notbirthday3", "notbirthday3"],
					["offense0", "offense0"],
					["offense1", "offense1"],
					["offense2", "offense2"],
					["offense3", "offense3"],
					["orderUber0", "orderUber0"],
					["orderUber1", "orderUber1"],
					["orderUber2", "orderUber2"],
					["orderUber3", "orderUber3"],
					["owlsound0", "owlsound0"],
					["owlsound1", "owlsound1"],
					["owlsound2", "owlsound2"],
					["owlsound3", "owlsound3"],
					["package0", "package0"],
					["package1", "package1"],
					["package2", "package2"],
					["package3", "package3"],
					["pickupline0", "pickupline0"],
					["pickupline1", "pickupline1"],
					["pickupline2", "pickupline2"],
					["pickupline3", "pickupline3"],
					["pigsound0", "pigsound0"],
					["pigsound1", "pigsound1"],
					["pigsound2", "pigsound2"],
					["pigsound3", "pigsound3"],
					["piratetalk0", "piratetalk0"],
					["piratetalk1", "piratetalk1"],
					["piratetalk2", "piratetalk2"],
					["piratetalk3", "piratetalk3"],
					["playagame0", "playagame0"],
					["playagame1", "playagame1"],
					["playagame2", "playagame2"],
					["playagame3", "playagame3"],
					["readapoem0", "readapoem0"],
					["readapoem1", "readapoem1"],
					["readapoem2", "readapoem2"],
					["readapoem3", "readapoem3"],
					["roostersound0", "roostersound0"],
					["roostersound1", "roostersound1"],
					["roostersound2", "roostersound2"],
					["roostersound3", "roostersound3"],
					["scarystory0", "scarystory0"],
					["scarystory1", "scarystory1"],
					["scarystory2", "scarystory2"],
					["scarystory3", "scarystory3"],
					["secret0", "secret0"],
					["secret1", "secret1"],
					["secret2", "secret2"],
					["secret3", "secret3"],
					["serande0", "serande0"],
					["serande1", "serande1"],
					["serande2", "serande2"],
					["serande3", "serande3"],
					["settemprature0", "settemprature0"],
					["settemprature1", "settemprature1"],
					["settemprature2", "settemprature2"],
					["settemprature3", "settemprature3"],
					["siblings0", "siblings0"],
					["siblings1", "siblings1"],
					["siblings2", "siblings2"],
					["siblings3", "siblings3"],
					["singmeasong0", "singmeasong0"],
					["singmeasong1", "singmeasong1"],
					["singmeasong2", "singmeasong2"],
					["singmeasong3", "singmeasong3"],
					["siri0", "siri0"],
					["siri1", "siri1"],
					["siri2", "siri2"],
					["siri3", "siri3"],
					["tellstory0", "tellstory0"],
					["tellstory1", "tellstory1"],
					["tellstory2", "tellstory2"],
					["tellstory3", "tellstory3"],
					["truck0", "truck0"],
					["truck1", "truck1"],
					["truck2", "truck2"],
					["truck3", "truck3"],
					["turkeysound0", "turkeysound0"],
					["turkeysound1", "turkeysound1"],
					["turkeysound2", "turkeysound2"],
					["turkeysound3", "turkeysound3"],
					["turnlights0", "turnlights0"],
					["turnlights1", "turnlights1"],
					["turnlights2", "turnlights2"],
					["turnlights3", "turnlights3"],
					["tv0", "tv0"],
					["tv1", "tv1"],
					["tv2", "tv2"],
					["tv3", "tv3"],
					["umbrella0", "umbrella0"],
					["umbrella1", "umbrella1"],
					["umbrella2", "umbrella2"],
					["umbrella3", "umbrella3"],
					["whatcanyoudo0", "whatcanyoudo0"],
					["whatcanyoudo1", "whatcanyoudo1"],
					["whatcanyoudo2", "whatcanyoudo2"],
					["whatcanyoudo3", "whatcanyoudo3"],
					["whatdoyoudo0", "whatdoyoudo0"],
					["whatdoyoudo1", "whatdoyoudo1"],
					["whatdoyoudo2", "whatdoyoudo2"],
					["whatdoyoudo3", "whatdoyoudo3"],
					["whatdoyouthinkofme0", "whatdoyouthinkofme0"],
					["whatdoyouthinkofme1", "whatdoyouthinkofme1"],
					["whatdoyouthinkofme2", "whatdoyouthinkofme2"],
					["whatdoyouthinkofme3", "whatdoyouthinkofme3"],
					["whatispassword0", "whatispassword0"],
					["whatispassword1", "whatispassword1"],
					["whatispassword2", "whatispassword2"],
					["whatispassword3", "whatispassword3"],
					["whatisyourquest0", "whatisyourquest0"],
					["whatisyourquest1", "whatisyourquest1"],
					["whatisyourquest2", "whatisyourquest2"],
					["whatisyourquest3", "whatisyourquest3"],
					["whatsoundfiretruck0", "whatsoundfiretruck0"],
					["whatsoundfiretruck1", "whatsoundfiretruck1"],
					["whatsoundfiretruck2", "whatsoundfiretruck2"],
					["whatsoundfiretruck3", "whatsoundfiretruck3"],
					["whatsup0", "whatsup0"],
					["whatsup1", "whatsup1"],
					["whatsup2", "whatsup2"],
					["whatsup3", "whatsup3"],
					["wheredoyoucomefrom0", "wheredoyoucomefrom0"],
					["wheredoyoucomefrom1", "wheredoyoucomefrom1"],
					["wheredoyoucomefrom2", "wheredoyoucomefrom2"],
					["wheredoyoucomefrom3", "wheredoyoucomefrom3"],
					["whereispassport0", "whereispassport0"],
					["whereispassport1", "whereispassport1"],
					["whereispassport2", "whereispassport2"],
					["whereispassport3", "whereispassport3"],
					["whoispresident0", "whoispresident0"],
					["whoispresident1", "whoispresident1"],
					["whoispresident2", "whoispresident2"],
					["whoispresident3", "whoispresident3"],
					["whoiswithyou0", "whoiswithyou0"],
					["whoiswithyou1", "whoiswithyou1"],
					["whoiswithyou2", "whoiswithyou2"],
					["whoiswithyou3", "whoiswithyou3"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Funpack samples",
		helpUrl: ""
	}
]);

Blockly.defineBlocksWithJsonArray([
	{
		type: "audio_spencer_sample_joke",
		message0: "joke %1",
		args0: [
			{
				type: "field_dropdown",
				name: "SAMPLE",
				options: [
					["0", "0"],
					["1", "1"],
					["2", "2"],
					["3", "3"],
					["4", "4"],
					["5", "5"],
					["6", "6"],
					["7", "7"],
					["8", "8"],
					["9", "9"],
					["10", "10"],
					["11", "11"],
					["12", "12"],
					["13", "13"],
					["14", "14"],
					["15", "15"],
					["16", "16"],
					["17", "17"],
					["18", "18"],
					["19", "19"],
					["20", "20"],
					["21", "21"],
					["22", "22"],
					["23", "23"],
					["24", "24"],
					["25", "25"],
					["26", "26"],
					["27", "27"],
					["28", "28"],
					["29", "29"],
					["30", "30"],
					["31", "31"],
					["32", "32"],
					["33", "33"],
					["34", "34"],
					["35", "35"],
					["36", "36"],
					["37", "37"],
					["38", "38"],
					["39", "39"],
					["40", "40"],
					["41", "41"],
					["42", "42"],
					["43", "43"],
					["44", "44"],
					["45", "45"],
					["46", "46"],
					["47", "47"],
					["48", "48"],
					["49", "49"],
					["50", "50"],
					["51", "51"],
					["52", "52"],
					["53", "53"],
					["54", "54"],
					["55", "55"],
					["56", "56"],
					["57", "57"],
					["58", "58"],
					["59", "59"],
					["60", "60"],
					["61", "61"],
					["62", "62"],
					["63", "63"],
					["64", "64"],
					["65", "65"],
					["66", "66"],
					["67", "67"],
					["68", "68"],
					["69", "69"],
					["70", "70"],
					["71", "71"],
					["72", "72"],
					["73", "73"],
					["74", "74"],
					["75", "75"],
					["76", "76"],
					["77", "77"],
					["78", "78"],
					["79", "79"],
					["80", "80"],
					["81", "81"],
					["82", "82"],
					["83", "83"],
					["84", "84"],
					["85", "85"],
					["86", "86"],
					["87", "87"],
					["88", "88"],
					["89", "89"],
					["90", "90"],
					["91", "91"],
					["92", "92"],
					["93", "93"],
					["94", "94"],
					["95", "95"],
					["96", "96"],
					["97", "97"],
					["98", "98"],
					["99", "99"],
					["100", "100"],
					["101", "101"],
					["102", "102"],
					["103", "103"],
					["104", "104"],
					["105", "105"],
					["106", "106"],
					["107", "107"],
					["108", "108"],
					["109", "109"],
				]
			}
		],
		output: "Spencer_Audio_Sample",
		outputShape: Blockly.OUTPUT_SHAPE_SQUARE,
		colour: Blockly.Msg.IO_HUE,
		tooltip: "Joke samples",
		helpUrl: ""
	}
]);