var MSG = {
  blocks: "Blocs",
  trashTooltip: "Supprimer tous les blocs.",
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catLists: "Listes",
  catColour: "Couleurs",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  listVariable: "liste",
  textVariable: "texte",
  xmlError: "Impossible de charger le fichier de sauvegarde.  Peut être a t-il été créé avec une autre version de Blockly?",
  badXml: "Erreur d’analyse du XML :\n%1\n\nSélectionner 'OK' pour abandonner vos modifications ou 'Annuler' pour continuer à modifier le XML.",
  uploadButton_span: "Téléverser",
  resetButton_span: "Réinitialiser",
  trashButton_span: "Supprimer tous les blocs",
  saveCodeButton_span: "Enregister le code Arduino",
  saveXMLButton_span: "Enregistrer le fichier Blockly",
  loadXMLfakeButton_span: "Ouvrir un fichier Blockly"
};
