var MSG = {
  blocks: "ブロック",
  trashTooltip: "すべてのブロックを消します。",
  catLogic: "論理",
  catLoops: "繰り返し",
  catMath: "数学",
  catText: "テキスト",
  catLists: "リスト",
  catColour: "色",
  catVariables: "変数",
  catFunctions: "関数",
  listVariable: "リスト",
  textVariable: "テキスト",
  xmlError: "保存されたファイルを読み込めませんでした。別のバージョンのブロックリーで作成された可能性があります。",
  badXml: "XML のエラーです:\n%1\n\nXML の変更をやめるには「OK」、編集を続けるには「キャンセル」を選んでください。",
  uploadButton_span: "Upload",
  resetButton_span: "Reset",
  trashButton_span: "Delete",
  saveCodeButton_span: "Save Arduino Code",
  saveXMLButton_span: "Save XML",
  loadXMLfakeButton_span: "Load XML"
};
