goog.require("Blockly");
goog.require("Blockly.Blocks");

goog.require('Blockly.Msg');
goog.require('Blockly.Msg.en');
goog.require('Blockly.Arduino.Msg.en');

goog.require("Blockly.Type");
goog.require("Blockly.Types");
goog.require("Blockly.StaticTyping");
goog.require("Blockly.Instances");
goog.require("Blockly.FieldInstance");
goog.require("Blockly.Ext.Procedures");
goog.require("Blockly.Ext.Block");
goog.require("Blockly.BlockVarTypes");
goog.require("Blockly.BlockTypes");
goog.require("Blockly.Ext.Functions");

goog.require("Blockly.Extensions.ReturnDecimal");
goog.require("Blockly.Extensions.ReturnBoolean");

goog.require("Blockly.Arduino");
goog.require("Blockly.Arduino.Boards");
goog.require("Blockly.Arduino.logic");
goog.require("Blockly.Arduino.text");
goog.require("Blockly.Arduino.spi");
goog.require("Blockly.Arduino.servo");
goog.require("Blockly.Arduino.lists");
goog.require("Blockly.Arduino.procedures");
goog.require("Blockly.Arduino.functions");
goog.require("Blockly.Arduino.time");
goog.require("Blockly.Arduino.map");
goog.require("Blockly.Arduino.colour");
goog.require("Blockly.Arduino.loops");
goog.require("Blockly.Arduino.stepper");
goog.require("Blockly.Arduino.IO");
goog.require("Blockly.Arduino.input");
goog.require("Blockly.Arduino.inputJayD");
goog.require("Blockly.Arduino.audio");
goog.require("Blockly.Arduino.JayDMix");
goog.require("Blockly.Arduino.pins");
goog.require("Blockly.Arduino.serial");
goog.require("Blockly.Arduino.tone");
goog.require("Blockly.Arduino.math");
goog.require("Blockly.Arduino.variables");
goog.require("Blockly.Arduino.MAKERphone");
goog.require("Blockly.Arduino.Nibble");
goog.require("Blockly.Arduino.Spencer");
goog.require("Blockly.Arduino.JayD");
goog.require("Blockly.Arduino.phone");
goog.require("Blockly.Arduino.display");
goog.require("Blockly.Arduino.display_sprite");
goog.require("Blockly.Arduino.ledmatrix");
goog.require("Blockly.Arduino.ledmatrixJayD");
goog.require("Blockly.Arduino.audio_spencer");
goog.require("Blockly.Arduino.wifi");
goog.require("Blockly.Arduino.spencer_speech");
goog.require("Blockly.Arduino.Wheelson");
goog.require("Blockly.Arduino.WheelsonIO");
goog.require("Blockly.Arduino.WheelsonCV");

goog.require("Blockly.Blocks.stepper");
goog.require("Blockly.Blocks.time");
goog.require("Blockly.Blocks.serial");
goog.require("Blockly.Blocks.io");
goog.require("Blockly.Blocks.input");
goog.require("Blockly.Blocks.inputJayD");
goog.require("Blockly.Blocks.audio");
goog.require("Blockly.Blocks.JayDMix");
goog.require("Blockly.Blocks.pins");
goog.require("Blockly.Blocks.tone");
goog.require("Blockly.Blocks.logo");
goog.require("Blockly.Blocks.variables");
goog.require("Blockly.Blocks.map");
goog.require("Blockly.Blocks.spi");
goog.require("Blockly.Blocks.Procedures");
goog.require("Blockly.Blocks.servo");
goog.require("Blockly.Ext.Blocks.Functions");
goog.require('Blockly.Blocks.functions');
goog.require('Blockly.Blocks.phone');
goog.require('Blockly.Blocks.display');
goog.require('Blockly.Blocks.display_sprite');
goog.require('Blockly.Blocks.ledmatrix');
goog.require('Blockly.Blocks.ledmatrixJayD');
goog.require('Blockly.Blocks.audio_spencer');
goog.require('Blockly.Blocks.wifi');
goog.require('Blockly.Blocks.spencer_speech');
goog.require('Blockly.Blocks.WheelsonIO');
goog.require('Blockly.Blocks.WheelsonCV');

Blockly.Device = "";

export default Blockly;
